#!/usr/bin/env python3
"""T12: read a connector's recorded fixtures with an *independent* parser.

The acceptance gate compares what `integral.connectors` extracts against what
this script wrote. That comparison is only worth making because the two sides
do not share an implementation:

* the connector uses the repo's own hand-rolled tree builder over stdlib
  `html.parser`, and a deliberately tiny selector subset (no combinators, no
  pseudo-classes) — see `src/integral/connectors.py`;
* this script uses `lxml` for parsing and BeautifulSoup's full CSS engine.

They disagree exactly where the small parser mishandles real markup — unclosed
tags, void elements, entity decoding — which is the risk a fixture recorded
from a live board exists to expose. A harness that derived both sides from one
parser would agree with itself whatever either did.

The output is **committed as data**, not regenerated by the gate. Re-running
this is a deliberate act (the fixtures were re-recorded); the gate reads the
frozen file, so a connector that stops parsing shows up as a fallen F1 rather
than as a quietly updated expectation.

Usage:
    python tools/annotate_connector_fixture.py connectors/trabajos_es \
        --out tests/fixtures/connectors/trabajos_es_expected.json
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

from bs4 import BeautifulSoup

from integral.connectors import load_connector

# Whitespace is normalised on both sides of the comparison. The two parsers
# collapse runs of space and newlines differently, and the gate is about which
# *field* was found, not about either one's whitespace policy.
WS = re.compile(r"\s+")


def norm(value: str) -> str:
    return WS.sub(" ", value).strip()


def extract(node: Any, css: str, attr: str | None) -> str | None:
    match = node.select_one(css)
    if match is None:
        return None
    value = match.get(attr, "") if attr else match.get_text(" ")
    return norm(str(value)) or None


def annotate(package: Path) -> dict[str, Any]:
    connector = load_connector(package)
    soup = BeautifulSoup((package / "fixture" / "list.html").read_text(encoding="utf-8"), "lxml")

    items: list[dict[str, str]] = []
    for card in soup.select(connector.list.item):
        row = {
            name: value
            for name, spec in connector.list.fields.items()
            if (value := extract(card, spec.css, spec.attr)) is not None
        }
        items.append(row)

    detail: dict[str, str] = {}
    detail_path = package / "fixture" / "detail.html"
    if connector.detail is not None and detail_path.exists():
        page = BeautifulSoup(detail_path.read_text(encoding="utf-8"), "lxml")
        detail = {
            name: value
            for name, spec in connector.detail.fields.items()
            if (value := extract(page, spec.css, spec.attr)) is not None
        }

    return {
        "package": package.name,
        "annotated_by": "lxml + BeautifulSoup full CSS, independent of integral.connectors",
        "list_items": items,
        "detail_fields": detail,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("package", type=Path)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    expected = annotate(args.package)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        json.dumps(expected, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(
        f"{args.out}: {len(expected['list_items'])} list items, "
        f"{len(expected['detail_fields'])} detail fields"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
